### ISSUE TITLE
KeyError: 'i'

### ISSUE THREAD

**Issue by kseistrup** [wdm0006/pygeohash#1]
There is no 'i' in geohash's alphabet, so while the example from the README
```py
>>> pgh.geohash_approximate_distance('shi3u', 'sh83n')
625441
>>>
```
works
```pytb
>>> pgh.geohash_haversine_distance('shi3u', 'sh83n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pygeohash/distances.py", line 73, in geohash_haversine_distance
    lat_1, lon_1 = decode(geohash_1)
  File "/usr/lib/python3.5/site-packages/pygeohash/geohash.py", line 72, in decode
    lat, lon, lat_err, lon_err = decode_exactly(geohash)
  File "/usr/lib/python3.5/site-packages/pygeohash/geohash.py", line 47, in decode_exactly
    cd = __decodemap[c]
KeyError: 'i'
```
doesn't.

**Comment by wdm0006** [comment]
Great catch, 

You're right, it's actually that "shi3u" is not a valid geohash, just some random letters.  Geohash approximate distance is simply counting up the number of leading characters that match, so it will happily take invalid geohashes, while Haversine distance actually converts them. 

With that in mind, I've added a default false flag to the geohash distance called check_validity, which will check that the inputs are in fact real geohashes before running. I've also changed the tests and README to use valid geohashes.
