### ISSUE TITLE
Error at install - SetuptoolsDeprecationWarning: Invalid dash-separated options

### ISSUE THREAD

**Issue by Djtrip83** [wdm0006/pygeohash#23]
Getting an error from today when trying to install pygeohash

Collecting pygeohash
  Using cached pygeohash-1.2.0.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info
      writing /tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-hhk8yq3i/pygeohash.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      /databricks/python3/lib/python3.8/site-packages/setuptools/dist.py:476: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-glpy_rrz/pygeohash_de5dd17dd66646f595a5d5fbbbfae548/setup.py", line 13, in <module>
          setup(
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          return distutils.core.setup(**attrs)
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 555, in run
          self.prune_file_list()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 621, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/databricks/python3/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Djtrip83** [comment]
Additional info - these are the setuptools versions I have pre-installed:

- setuptools==52.0.0
- setuptools-git==1.2

**Comment by Djtrip83** [comment]
Workaround in place for now (for those stuck that needs a quick solution) but not ideal so please update this very good package :)

Step after all other packages (incl. setuptools and excl. pygeohash) are installed/imported:
- !pip install --upgrade setuptools==70.0.0 ##interim to step to meet pygeohash compatibility
- !pip install pygeohash
- import pygeohash as pgh
